### ISSUE TITLE
Bad Request受信後、クライアント（metemcyber_ctl.sh）が落ちる

### ISSUE THREAD

**Issue by Hidetomi** [nttcom/metemcyber#10]
### 区分

- [ ] バグ
- [x] 改善要望

### 起きた事象

CTIトークンの購入メニューで 1 を入力しENTER、  
`requests.exceptions.HTTPError: 400 Client Error: Bad Request`を受信後スクリプトが停止する。

### 期待する動作

- 何らかのエラーメッセージが出力され、メニューが再表示される。
- ユーザーは継続して次の操作が行える。
- エラーメッセージからユーザーが取るべきアクションが分かる。
  - hint、tips、READMEへの誘導など。

### 実行環境（ホスト）

- OS
  - Windows10 pro 2004
- バージョン
  - 19041.630
- その他
  - Hypter-V上でUbuntuを起動

### 実行環境（ゲスト）

- OS
  - Ubuntu
- バージョン
  - 20.04.1 LTS (Focal Fossa)

### gitハッシュ値

```
umaki@metmecyber:~/metemcyber$ git rev-parse HEAD
dea7cec41d572d186533e13cf793262915c53d00
```

### ログ等

事象発生時のターミナル画面

```
OSINT - Rise of One More Mirai Worm Variantを購入しますか
[1]購入する
[2]キャンセル
1
Traceback (most recent call last):
  File "src/client.py", line 599, in <module>
    main(ARGS)
  File "src/client.py", line 562, in main
    controller.menu()
  File "src/client.py", line 135, in menu
    getattr(self, self.state)()
  File "src/client.py", line 154, in shopping
    self.model.buy(address)
  File "/usr/src/myapp/src/client_model.py", line 378, in buy
    self.inventory.buy(token_address, allow_cheaper=True)
  File "/usr/src/myapp/src/inventory.py", line 174, in buy
    self.broker.buy(
  File "/usr/src/myapp/src/inventory.py", line 439, in buy
    self.ctibroker.buy_token(
  File "/usr/src/myapp/src/ctibroker.py", line 54, in buy_token
    tx_hash = func.transact({'value': wei})
  File "/usr/local/lib/python3.8/dist-packages/web3/contract.py", line 993, in transact
    return transact_with_contract_function(
  File "/usr/local/lib/python3.8/dist-packages/web3/contract.py", line 1588, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/usr/local/lib/python3.8/dist-packages/web3/module.py", line 54, in caller
    (method_str, params), response_formatters = method.process_params(module, *args, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/dist-packages/web3/method.py", line 176, in process_params
    params = self.input_munger(module, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/web3/method.py", line 168, in input_munger
    root_munger(module, *args, **kwargs),
  File "/usr/local/lib/python3.8/dist-packages/web3/eth.py", line 383, in send_transaction_munger
    get_buffered_gas_estimate(self.web3, transaction),
  File "/usr/local/lib/python3.8/dist-packages/web3/_utils/transactions.py", line 127, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/usr/local/lib/python3.8/dist-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/usr/local/lib/python3.8/dist-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/signing.py", line 150, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/exception_retry_request.py", line 104, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/providers/rpc.py", line 92, in make_request
    raw_response = make_post_request(
  File "/usr/local/lib/python3.8/dist-packages/web3/_utils/request.py", line 40, in make_post_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://rpc.metemcyber.ntt.com/
umaki@metmecyber:~/metemcyber$
```

**Comment by nitky** [comment]
transact実行時に
`400 Client Error: Bad Request for url: https://rpc.metemcyber.ntt.com/`
という表示が出ているため、transactを実行するためのパラメータに問題があると考えられます。
これは、間違った署名鍵が指定されている場合に特に多くみられるエラーです。
